#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /login_check

app_index:
    path: /
    controller: Guess\Controller\HelloController::index

api_player_create:
  path: /api/players
  methods: POST
  controller: Guess\Controller\Player\PlayerController::index